@extends('screen.footer.master.index')
@section('content')
<div class="container about">
	<h2>Term Of Services</h2><hr>
	<p style="text-align:justify"><span style="font-size:18px"><strong>Chấp Thuận Điều Khoản &amp; Điều Kiện</strong></span></p>

<p style="text-align:justify"><span style="font-size:14px">&nbsp; &nbsp; &nbsp; &nbsp;Vui l&ograve;ng đọc kỹ c&aacute;c Điều Khoản &amp; Điều Kiện n&agrave;y trước khi truy nhập v&agrave; sử dụng dịch vụ tr&ecirc;n website đăng tuyển dụng TopDev.vn (sau đ&acirc;y gọi l&agrave; &ldquo;Website TopDev&rdquo;) của C&ocirc;ng ty Cổ phần Applancer (sau đ&acirc;y gọi l&agrave; &ldquo;C&ocirc;ng ty&rdquo;). Bằng việc chấp thuận Điều Khoản &amp; Điều Kiện n&agrave;y, bạn đồng &yacute; bị r&agrave;ng buộc bởi c&aacute;c quy định về sử dụng Dịch vụ tr&ecirc;n Website TopDev. Nếu bạn c&oacute; bất kỳ c&acirc;u hỏi n&agrave;o về bản thỏa thuận n&agrave;y, vui l&ograve;ng li&ecirc;n hệ ch&uacute;ng t&ocirc;i qua email&nbsp;<a href="mailto:contact@topdev.vn"><span style="color:#e74c3c">contact@topdev.vn</span></a><span style="color:#e74c3c">.</span></span></p>

<p style="text-align:justify"><span style="font-size:18px"><strong>Dịch Vụ Của TopDev</strong></span></p>

<p style="text-align:justify"><span style="font-size:14px">&nbsp; &nbsp; &nbsp; &nbsp;TopDev.vn l&agrave; một trang Web tr&ecirc;n mạng Internet được thiết kế cho ph&eacute;p những người sử dụng đăng th&ocirc;ng b&aacute;o tuyển dụng v&agrave;/hoặc xem c&aacute;c c&ocirc;ng việc do những người sử dụng kh&aacute;c đăng l&ecirc;n, hoặc tương t&aacute;c với những người sử dụng kh&aacute;c. TopDev.vn do C&ocirc;ng ty Applancer JSC sở hữu v&agrave; điều h&agrave;nh. Website TopDev chứa v&agrave; c&oacute; thể chứa c&aacute;c th&ocirc;ng tin, tin tức, c&aacute;c &yacute; kiến, văn bản, đồ hoạ, c&aacute;c li&ecirc;n kết, sản phẩm nghệ thuật điện tử, h&igrave;nh ảnh động, &acirc;m thanh, video, phần mềm, tranh ảnh, &acirc;m nhạc, tiếng động v&agrave; c&aacute;c nội dung, dữ liệu kh&aacute;c (gọi chung l&agrave; &ldquo;nội dung&rdquo;) được định dạng, tổ chức v&agrave; thu thập dưới nhiều h&igrave;nh thức kh&aacute;c nhau m&agrave; người sử dụng c&oacute; thể truy nhập tới được, gồm c&aacute;c thư mục, cơ sở dữ liệu v&agrave; c&aacute;c v&ugrave;ng tr&ecirc;n website của TopDev.vn m&agrave; người sử dụng c&oacute; thể thay đổi được, chẳng hạn như đăng quảng c&aacute;o tuyển dụng, tải l&ecirc;n c&aacute;c tệp đa phương tiện, đăng k&yacute; c&aacute;c hồ sơ người sử dụng v&agrave; tạo c&aacute;c hồ sơ tự th&ocirc;ng b&aacute;o (&ldquo;v&ugrave;ng tương t&aacute;c&rdquo;).</span></p>

<p style="text-align:justify"><span style="font-size:14px">&nbsp; &nbsp; &nbsp; &nbsp;Để c&oacute; thể sử dụng đầy đủ tiện &iacute;ch dịch vụ tr&ecirc;n Website TopDev, bạn cần phải đăng k&yacute; tạo lập một t&agrave;i khoản sử dụng v&agrave; cung cấp Website TopDev một số th&ocirc;ng tin c&aacute; nh&acirc;n nhất định bao gồm m&agrave; kh&ocirc;ng giới hạn bởi địa chỉ email để phục vụ cho việc li&ecirc;n lạc giao tiếp giữa bạn v&agrave; Website TopDev cũng như những người sử dụng kh&aacute;c sau n&agrave;y. Bằng việc đăng k&yacute; n&agrave;y, bạn đồng &yacute; nhận c&aacute;c Thư th&ocirc;ng b&aacute;o, c&aacute;c thư điện tử hoặc c&aacute;c h&igrave;nh thức truyền th&ocirc;ng kh&aacute;c về c&aacute;c sản phẩm v&agrave; dịch vụ của Website TopDev. Bất cứ khi n&agrave;o bạn kh&ocirc;ng mong muốn nhận c&aacute;c thư điện tử n&agrave;y nữa, th&igrave; bạn h&atilde;y th&ocirc;ng b&aacute;o cho Website TopDev bằng c&aacute;ch chọn chức năng hủy đăng k&yacute; c&oacute; sẵn tr&ecirc;n Website TopDev hoặc tại b&ecirc;n dưới của c&aacute;c thư điện tử của Website TopDev. C&aacute;c th&ocirc;ng tin c&aacute; nh&acirc;n của bạn sẽ được bảo quản v&agrave; xử l&yacute; một c&aacute;ch bảo mật theo Ch&iacute;nh S&aacute;ch Bảo Mật của Website TopDev.</span></p>

<p style="text-align:justify"><span style="font-size:14px">&nbsp; &nbsp; &nbsp; &nbsp;Bạn c&oacute; thể đặt mua sử dụng c&aacute;c dịch vụ hoặc sản phẩm với c&aacute;c mức gi&aacute; ni&ecirc;m yết c&oacute; sẵn tr&ecirc;n Website TopDev v&agrave; việc đặt mua n&agrave;y của bạn sẽ t&ugrave;y thuộc v&agrave;o chấp thuận một phần hoặc to&agrave;n bộ điều kiện đặt h&agrave;ng n&agrave;y của Website TopDev. Việc chấp thuận n&agrave;y của Website TopDev chỉ c&oacute; hiệu lực r&agrave;ng buộc khi bạn đ&atilde; thanh to&aacute;n hoặc c&aacute;c th&ocirc;ng tin về thanh to&aacute;n của bạn đ&atilde; được x&aacute;c nhận.</span></p>

<p style="text-align:justify"><span style="font-size:14px">&nbsp; &nbsp; &nbsp; &nbsp;Website TopDev bảo lưu quyền thay đổi c&aacute;c dịch vụ, sản phẩm, biểu gi&aacute; v&agrave; phương thức t&iacute;nh gi&aacute; v&agrave; c&aacute;c thay đổi kh&aacute;c của Website TopDev từng thời gian m&agrave; kh&ocirc;ng phải th&ocirc;ng b&aacute;o trước cho người sử dụng nếu thấy ph&ugrave; hợp.</span></p>

<p><span style="font-size:18px"><strong>Dịch Vụ Đặt Mua V&agrave; Thanh To&aacute;n</strong></span></p>

<ol style="line-height: 2">
	<li><span style="font-size:14px">Bạn c&oacute; thể mua một hoặc nhiều dịch vụ c&oacute; sẵn trong Danh s&aacute;ch Dịch vụ của TopDev th&ocirc;ng qua Đơn đặt h&agrave;ng v&agrave;/hoặc Hợp đồng Dịch vụ. Nếu dịch vụ Kh&aacute;ch h&agrave;ng mua l&agrave; Dịch vụ Đăng tuyển:</span></li>
	<li>
	<ul>
		<li><span style="font-size:14px">Vị tr&iacute; đăng tuyển sẽ được đăng tr&ecirc;n Website TopDev trong 30 (ba mươi) ng&agrave;y kể từ ng&agrave;y k&iacute;ch hoạt. Ti&ecirc;u đề c&ocirc;ng việc kh&ocirc;ng được thay đổi sau khi vị tr&iacute; đăng tuyển đ&atilde; được k&iacute;ch hoạt đăng tr&ecirc;n Webiste TopDev.</span></li>
		<li><span style="font-size:14px">Mỗi vị tr&iacute; đăng tuyển chỉ được bao gồm 01 (một) ti&ecirc;u đề đăng tuyển c&ugrave;ng 01 (một) m&ocirc; tả c&ocirc;ng việc v&agrave; y&ecirc;u cầu c&ocirc;ng việc.</span></li>
	</ul>
	</li>
	<li><span style="font-size:14px">Dịch vụ của TopDev l&agrave; dịch vụ trả trước hoặc trả sau bằng tiền mặt, chuyển khoản hoặc thẻ t&iacute;n dụng. Danh s&aacute;ch c&aacute;c loại thẻ t&iacute;n dụng được chấp thuận sẽ được c&ocirc;ng bố tr&ecirc;n Website TopDev. Ph&iacute; Dịch vụ phải được thanh to&aacute;n chậm nhất v&agrave;o Ng&agrave;y thanh to&aacute;n quy định tr&ecirc;n Đơn đặt h&agrave;ng. C&aacute;c Dịch vụ đặt mua sẽ được k&iacute;ch hoạt trong v&ograve;ng 3 ng&agrave;y l&agrave;m việc kể từ ng&agrave;y Kh&aacute;ch h&agrave;ng thanh to&aacute;n Ph&iacute; Dịch vụ. Nếu qu&aacute; Ng&agrave;y thanh to&aacute;n m&agrave; Kh&aacute;ch h&agrave;ng vẫn chưa thực hiện thanh to&aacute;n Ph&iacute; Dịch vụ, th&igrave; C&ocirc;ng ty c&oacute; quyền tạm ngưng cung cấp dịch vụ cho đến khi việc thanh to&aacute;n được thực hiện đầy đủ.</span></li>
	<li><span style="font-size:14px">C&ocirc;ng ty sẽ xuất H&oacute;a đơn Thuế GTGT theo quy định của ph&aacute;p luật Việt Nam hiện h&agrave;nh ngay khi Kh&aacute;ch h&agrave;ng y&ecirc;u cầu. Kh&aacute;ch h&agrave;ng chịu tr&aacute;ch nhiệm về t&iacute;nh ch&iacute;nh x&aacute;c của th&ocirc;ng tin xuất H&oacute;a đơn Thuế GTGT.</span></li>
</ol>

<p><span style="font-size:18px"><strong>Điều Khoản Về Sử Dụng Dịch Vụ</strong></span></p>

<ol>
	<li><span style="font-size:14px">Sau khi bạn đ&atilde; thanh to&aacute;n Ph&iacute; Dịch vụ v&agrave;/hoặc k&iacute;ch hoạt c&aacute;c Dịch vụ đ&atilde; đặt mua, ch&uacute;ng t&ocirc;i sẽ kh&ocirc;ng chấp nhận bất kỳ y&ecirc;u cầu tạm ngưng hoặc hủy bỏ c&aacute;c Dịch vụ đ&atilde; đặt mua, hoặc ho&agrave;n Ph&iacute; Dịch vụ, hoặc thay đổi dịch vụ.</span></li>
	<li><span style="font-size:14px">Bạn sẽ tự tạo một t&agrave;i khoản với mật khẩu để sử dụng dịch vụ tr&ecirc;n Website TopDev.</span></li>
	<li><span style="font-size:14px">Bạn được quyền đăng tải nội dung th&ocirc;ng tin đăng tuyển của m&igrave;nh v&agrave;/hoặc đường dẫn tr&ecirc;n Website TopDev đến nội dung th&ocirc;ng tin tuyển dụng tại trang web của m&igrave;nh v&agrave; ho&agrave;n to&agrave;n chịu tr&aacute;ch nhiệm về t&iacute;nh ch&iacute;nh x&aacute;c v&agrave; hợp ph&aacute;p của c&aacute;c nội dung n&agrave;y.</span></li>
	<li><span style="font-size:14px">Bạn phải k&iacute;ch hoạt Dịch vụ đ&atilde; mua trong thời hạn sử dụng. Khi hết thời hạn sử dụng, bất kỳ Dịch vụ đ&atilde; mua nhưng chưa được k&iacute;ch hoạt sẽ kh&ocirc;ng c&ograve;n gi&aacute; trị sử dụng.</span></li>
	<li><span style="font-size:14px">Trường hợp do lỗi cố &yacute; của ch&uacute;ng t&ocirc;i m&agrave; sau 7 (bảy) ng&agrave;y l&agrave;m việc kể từ ng&agrave;y bạn c&oacute; th&ocirc;ng b&aacute;o nhắc nhở bằng văn bản về vi phạm m&agrave; ch&uacute;ng t&ocirc;i vẫn chưa tiến h&agrave;nh khắc phục sai phạm n&agrave;y, ch&uacute;ng t&ocirc;i sẽ ho&agrave;n trả cho bạn Ph&iacute; Dịch vụ tương ứng với Dịch vụ chưa sử dụng theo Đơn đặt h&agrave;ng/Hợp đồng Dịch vụ m&agrave; ch&uacute;ng t&ocirc;i kh&ocirc;ng cung cấp theo đ&uacute;ng thỏa thuận giữa hai b&ecirc;n.</span></li>
</ol>

<p><span style="font-size:18px"><strong>Quyền V&agrave; Tr&aacute;ch Nhiệm Của Người Sử Dụng</strong></span></p>

<p><span style="font-size:14px">&nbsp; &nbsp; &nbsp; &nbsp;<strong>Truy cập Website&nbsp;TopDev.vn.</strong>&nbsp;Bạn c&oacute; tr&aacute;ch nhiệm tự cung cấp tất cả phần cứng, phần mềm, số điện thoại hoặc c&aacute;c thiết bị li&ecirc;n lạc kh&aacute;c v&agrave;/hoặc dịch vụ kết nối tới Internet v&agrave; truy cập Website TopDev.vn, đồng thời c&oacute; tr&aacute;ch nhiệm trả mọi khoản ph&iacute; truy cập Internet, ph&iacute; điện thoại hoặc c&aacute;c khoản ph&iacute; kh&aacute;c ph&aacute;t sinh trong qu&aacute; tr&igrave;nh kết nối Internet v&agrave; truy cập Website TopDev.</span></p>

<p><span style="font-size:14px">&nbsp; &nbsp; &nbsp; &nbsp;<strong>Đạo đức người sử dụng.</strong>&nbsp;Khi sử dụng Dịch vụ của TopDev v&agrave; truy cập v&agrave;o Website TopDev, bạn nhận thức đầy đủ c&aacute;c điều cấm sau:</span></p>

<ol>
	<li><span style="font-size:14px">Chống Nh&agrave; nước Cộng ho&agrave; x&atilde; hội chủ nghĩa Việt Nam, ph&aacute; hoại khối đo&agrave;n kết to&agrave;n d&acirc;n, tuy&ecirc;n truyền, xuy&ecirc;n tạc, k&iacute;ch động hoặc cung cấp th&ocirc;ng chống ph&aacute; Nh&agrave; nước Việt Nam;</span></li>
	<li><span style="font-size:14px">K&iacute;ch động bạo lực, tuy&ecirc;n truyền chiến tranh x&acirc;m lược, g&acirc;y hận th&ugrave; giữa c&aacute;c d&acirc;n tộc v&agrave; nh&acirc;n d&acirc;n c&aacute;c nước, k&iacute;ch động d&acirc;m &ocirc;, đồi trụy, tội &aacute;c, tệ nạn x&atilde; hội, m&ecirc; t&iacute;n dị đoan, ph&aacute; hoại thuần phong mỹ tục của d&acirc;n tộc;</span></li>
	<li><span style="font-size:14px">Tiết lộ b&iacute; mật nh&agrave; nước, b&iacute; mật qu&acirc;n sự, an ninh, kinh tế, đối ngoại v&agrave; những b&iacute; mật kh&aacute;c đ&atilde; được ph&aacute;p luật quy định;</span></li>
	<li><span style="font-size:14px">Xuy&ecirc;n tạc, vu khống, x&uacute;c phạm uy t&iacute;n của tổ chức, danh dự, nh&acirc;n phẩm, uy t&iacute;n của c&ocirc;ng d&acirc;n;</span></li>
	<li><span style="font-size:14px">Quảng c&aacute;o, tuy&ecirc;n truyền h&agrave;ng ho&aacute;, dịch vụ thuộc danh mục cấm đ&atilde; được ph&aacute;p luật quy định;</span></li>
	<li><span style="font-size:14px">Đề cập đến c&aacute;c vấn đề ch&iacute;nh trị v&agrave; t&ocirc;n gi&aacute;o;</span></li>
	<li><span style="font-size:14px">Sử dụng c&aacute;c từ ngữ v&ocirc; văn h&oacute;a vi phạm truyền thống đạo đức của Việt Nam;</span></li>
	<li><span style="font-size:14px">Hạn chế hoặc ngăn cản người sử dụng kh&aacute;c sử dụng v&agrave; hưởng c&aacute;c t&iacute;nh năng tương t&aacute;c;</span></li>
	<li><span style="font-size:14px">Gửi hoặc chuyển c&aacute;c th&ocirc;ng tin bất hợp ph&aacute;p, đe doạ, lạm dụng, b&ocirc;i nhọ, n&oacute;i xấu, khi&ecirc;u d&acirc;m, phi thẩm mỹ, x&uacute;c phạm hoặc bất kỳ loại th&ocirc;ng tin kh&ocirc;ng đứng đắn n&agrave;o, bao gồm nhưng kh&ocirc;ng hạn chế việc truyền b&aacute; tin tức g&oacute;p phần hay khuyến kh&iacute;ch h&agrave;nh vi phạm tội, g&acirc;y ra tr&aacute;ch nhiệm ph&aacute;p l&yacute; d&acirc;n sự hoặc vi phạm ph&aacute;p luật đia phương, li&ecirc;ng bang, quốc gia hoặc quốc tế;</span></li>
	<li><span style="font-size:14px">Gửi hay chuyển c&aacute;c th&ocirc;ng tin, phần mềm, hoặc c&aacute;c t&agrave;i liệu kh&aacute;c bất kỳ, vi phạm hoặc x&acirc;m phạm c&aacute;c quyền của những người kh&aacute;c, trong đ&oacute; bao gồm cả t&agrave;i liệu x&acirc;m phạm đến quyền ri&ecirc;ng tư hoặc c&ocirc;ng khai, hoặc t&agrave;i liệu được bảo vệ bản quyền, t&ecirc;n thương mại hoặc quyền sở hữu kh&aacute;c, hoặc c&aacute;c sản phẩm ph&aacute;i sinh m&agrave; kh&ocirc;ng được sự cho ph&eacute;p của người chủ sở hữu hoặc người c&oacute; quyền hợp ph&aacute;p;</span></li>
	<li><span style="font-size:14px">Gửi hoặc chuyển th&ocirc;ng tin, phần mềm hoặc t&agrave;i liệu bất kỳ c&oacute; chứa virus hoặc một th&agrave;nh phần g&acirc;y hại kh&aacute;c;</span></li>
	<li><span style="font-size:14px">Thay đổi, l&agrave;m hư hại hoặc x&oacute;a nội dung bất kỳ hoặc c&aacute;c phương tiện kh&aacute;c m&agrave; kh&ocirc;ng phải l&agrave; nội dung thuộc sở hữu của bạn, hoặc g&acirc;y trợ ngại cho những người kh&aacute;c truy cập đến Website TopDev;</span></li>
	<li><span style="font-size:14px">Ph&aacute; vỡ luồng th&ocirc;ng tin b&igrave;nh thường trong một v&ugrave;ng tương t&aacute;c;</span></li>
	<li><span style="font-size:14px">Tuy&ecirc;n bố c&oacute; li&ecirc;n hệ với hay ph&aacute;t ng&ocirc;n cho một doanh nghiệp, hiệp hội, thể chế hay tổ chức n&agrave;o kh&aacute;c m&agrave; bạn kh&ocirc;ng được uỷ quyền tuy&ecirc;n bố mối li&ecirc;n hệ đ&oacute;;</span></li>
	<li><span style="font-size:14px">Sử dụng Website TopDev cho những mục đ&iacute;ch phi ph&aacute;p, bao gồm nhưng kh&ocirc;ng giới hạn h&agrave;nh vi vi phạm một quy tắc, ch&iacute;nh s&aacute;ch hay hướng dẫn sử dụng n&agrave;o của nh&agrave; cung cấp dịch vụ Internet cho bạn hay c&aacute;c dịch vụ trực tuyến.</span></li>
</ol>

<p><span style="font-size:18px"><strong>C&aacute;c V&ugrave;ng Tương T&aacute;c</strong></span></p>

<p><span style="font-size:14px">&nbsp; &nbsp; &nbsp; &nbsp;Bạn thừa nhận, Website TopDev c&oacute; thể chứa c&aacute;c v&ugrave;ng tương t&aacute;c kh&aacute;c nhau, bao gồm nhưng kh&ocirc;ng hạn chế với c&aacute;c c&ocirc;ng việc. Những v&ugrave;ng tương t&aacute;c n&agrave;y cho ph&eacute;p phản hồi đến Website TopDev v&agrave; tương t&aacute;c thời gian thực giữa những người sử dụng. Bạn cũng hiểu rằng, Website TopDev kh&ocirc;ng kiểm so&aacute;t c&aacute;c th&ocirc;ng b&aacute;o, th&ocirc;ng tin hoặc c&aacute;c tệp được ph&acirc;n phối tới c&aacute;c v&ugrave;ng tương t&aacute;c như vậy v&agrave; rằng, Website TopDev c&oacute; thể cho bạn v&agrave; những người sử dụng kh&aacute;c khả năng tạo v&agrave; quản l&yacute; một v&ugrave;ng tương t&aacute;c. Tuy nhi&ecirc;n, Website TopDev, c&ocirc;ng ty mẹ, hoặc c&aacute;c chi nh&aacute;nh, cũng như c&aacute;c gi&aacute;m đốc, nh&acirc;n vi&ecirc;n, những người l&agrave;m thu&ecirc; v&agrave; c&aacute;c đại l&yacute; tương ứng kh&ocirc;ng chịu tr&aacute;ch nhiệm về nội dung trong v&ugrave;ng tương t&aacute;c bất kỳ.</span></p>

<p><span style="font-size:14px">&nbsp; &nbsp; &nbsp; &nbsp;Việc sử dụng v&agrave;/hoặc quản l&yacute; một v&ugrave;ng tương t&aacute;c của bạn sẽ bị chi phối bởi Bản thoả thuận n&agrave;y v&agrave; c&aacute;c quy tắc bổ sung bất kỳ, hoặc bởi c&aacute;c thủ tục hoạt động của v&ugrave;ng tương t&aacute;c bất kỳ do bạn hay người sử dụng kh&aacute;c thiết lập. Bạn c&ocirc;ng nhận rằng, Website TopDev kh&ocirc;ng thể v&agrave; kh&ocirc;ng c&oacute; &yacute; định s&agrave;ng lọc c&aacute;c th&ocirc;ng tin trước. Ngo&agrave;i ra, v&igrave; Website TopDev khuyến kh&iacute;ch li&ecirc;n lạc mở v&agrave; kh&ocirc;ng thi&ecirc;n vị trong c&aacute;c v&ugrave;ng tương t&aacute;c n&ecirc;n Website TopDev kh&ocirc;ng thể x&aacute;c định trước mức độ ch&iacute;nh x&aacute;c hoặc sự ph&ugrave; hợp đối với bản Thoả thuận n&agrave;y về nội dung bất kỳ được chuyển đi trong v&ugrave;ng tương t&aacute;c. Website TopDev kh&ocirc;ng chịu tr&aacute;ch nhiệm với việc s&agrave;ng lọc, lập ch&iacute;nh s&aacute;ch, hiệu chỉnh, duyệt hoặc gi&aacute;m s&aacute;t nội dung bất kỳ trong một v&ugrave;ng tương t&aacute;c.</span></p>

<p><span style="font-size:14px">&nbsp; &nbsp; &nbsp; &nbsp;Mặc d&ugrave; vậy, bạn cũng đồng &yacute; rằng Website TopDev c&oacute; quyền gi&aacute;m s&aacute;t mọi v&ugrave;ng tương t&aacute;c, đ&ocirc;i l&uacute;c để lộ th&ocirc;ng tin n&agrave;o đ&oacute; nếu cần thiết theo y&ecirc;u cầu luật ph&aacute;p, hoặc y&ecirc;u cầu kh&aacute;c của ch&iacute;nh phủ đối với hoạt động của v&ugrave;ng tương t&aacute;c, hoặc để tự bảo vệ m&igrave;nh hay những người sử dụng kh&aacute;c. Nếu được th&ocirc;ng b&aacute;o nội dung dẫn ra kh&ocirc;ng ph&ugrave; hợp với bản Thỏa thuận n&agrave;y, Website TopDev c&oacute; thể thận trọng điều tra v&agrave; x&aacute;c định để loại bỏ, hoặc y&ecirc;u cầu người sử dụng bỏ nội dung đ&oacute;. Website TopDev giữ quyền cấm c&aacute;c h&agrave;nh động, truyền đạt tin tức hoặc nội dung trong phạm vi v&ugrave;ng tương t&aacute;c, hoặc soạn thảo, từ chối gửi, hoặc loại bỏ nội dung bất kỳ, to&agrave;n thể hay từng phần m&agrave; với đặc quyền của m&igrave;nh, ch&uacute;ng t&ocirc;i cho rằng (i) vi phạm c&aacute;c điều khoản ti&ecirc;u chuẩn l&uacute;c đ&oacute; của bản Thỏa thuận n&agrave;y hoặc chuẩn bất kỳ kh&aacute;c nằm trong ch&iacute;nh s&aacute;ch của TopDev.vn vẫn c&ograve;n hiệu lực v&agrave;o l&uacute;c đ&oacute;, (ii) bất lợi với c&aacute;c quyền của mọi người sử dụng, của Website TopDev hoặc c&aacute;c nh&oacute;m thứ ba kh&aacute;c, (iii) vi phạm luật hiện h&agrave;nh hoặc (iv) những điều kh&ocirc;ng hay kh&aacute;c.</span></p>

<p><span style="font-size:18px"><strong>C&aacute;c Quyền Sở Hữu Tr&iacute; Tuệ</strong></span></p>

<p><span style="font-size:14px">&nbsp; &nbsp; &nbsp; &nbsp;<strong>Nội dung Website nghề nghiệp&nbsp;TopDev.vn.</strong>&nbsp;Bạn thừa nhận, TopDev Website cho ph&eacute;p truy cập đến Nội dung được bảo vệ bản quyền, t&ecirc;n thương mại v&agrave; c&aacute;c quyền sở hữu kh&aacute;c (kể cả quyền sở hữu tr&iacute; tuệ) (&ldquo;Quyền Sở hữu Tr&iacute; tuệ&rdquo;), v&agrave; thừa nhận c&aacute;c quyền sở hữu tr&iacute; tuệ đ&oacute; l&agrave; hợp lệ v&agrave; được bảo vệ tr&ecirc;n mọi phương tiện truyền th&ocirc;ng hiện c&oacute; v&agrave; sau n&agrave;y, trừ những điểm n&ecirc;u r&otilde; r&agrave;ng dưới đ&acirc;y, việc sử dụng nội dung của bạn sẽ được quản l&yacute; theo c&aacute;c luật bản quyền v&agrave; c&aacute;c luật sở hữu tr&iacute; tuệ hiện h&agrave;nh kh&aacute;c.</span></p>

<p><span style="font-size:14px">&nbsp; &nbsp; &nbsp; &nbsp;Bạn đồng &yacute; v&agrave; thừa nhận rằng tất cả c&aacute;c nội dung tr&ecirc;n TopDev Website bao gồm nhưng kh&ocirc;ng giới hạn bởi c&aacute;c sơ yếu l&yacute; lịch sẽ thuộc quyền sở hữu tr&iacute; tuệ duy nhất của Website TopDev v&agrave; Applancer v&agrave; bạn kh&ocirc;ng được quyền thay đổi, sao ch&eacute;p, m&ocirc; phỏng, truyền, ph&acirc;n phối, c&ocirc;ng bố, tạo ra c&aacute;c sản phẩm ph&aacute;i sinh, hiển thị hoặc chuyển giao, hoặc khai th&aacute;c nhằm mục đ&iacute;ch thương mại bất kỳ phần n&agrave;o của nội dung, to&agrave;n bộ hay từng phần. Tuy nhi&ecirc;n, bạn c&oacute; thể (i) tạo một bản sao dưới dạng số hoặc h&igrave;nh thức kh&aacute;c để phần cứng v&agrave; phần mềm m&aacute;y t&iacute;nh của bạn c&oacute; thể truy cập v&agrave; xem được nội dung, (ii) in một bản sao của từng đoạn nội dung, (iii) tạo v&agrave; ph&acirc;n phối một số lượng hợp l&yacute; c&aacute;c bản sao nội dung, to&agrave;n bộ hay từng phần, ở dạng bản in hoặc bản điện tử để d&ugrave;ng nội bộ.</span></p>

<p><span style="font-size:14px">&nbsp; &nbsp; &nbsp; &nbsp;Bất kỳ bản sao nội dung được ph&eacute;p n&agrave;o cũng phải được t&aacute;i tạo ở dạng kh&ocirc;ng thể biến đổi được c&aacute;c th&ocirc;ng tri bất kỳ chứa trong nội dung, chẳng hạn như tất cả c&aacute;c th&ocirc;ng tri về Quyền Sở hữu Tr&iacute; tuệ, v&agrave; c&aacute;c nguồn th&ocirc;ng tin ban đầu cho &ldquo;website nghề nghiệp TopDev.vn&rdquo; v&agrave; địa chỉ mạng (URL) của n&oacute;. Bạn sẽ kh&ocirc;ng c&oacute; bất kỳ Quyền Sở hữu Tr&iacute; tuệ n&agrave;o qua việc tải xuống hoặc in nội dung. Bất kể c&aacute;c bản sao hoặc việc sử dụng tr&aacute;i ph&eacute;p n&agrave;o đối với nội dung n&agrave;o cho mục đ&iacute;ch thương mại sẽ bị coi l&agrave; vi phạm v&agrave; bị xử l&yacute; theo quy định c&oacute; li&ecirc;n quan của ph&aacute;p luật v&agrave; c&aacute;c điều khoản quy định tại bản thỏa thuận n&agrave;y.</span></p>

<p><span style="font-size:14px">&nbsp; &nbsp; &nbsp; &nbsp;<strong>Nội dung do Người sử dụng cung cấp.</strong>&nbsp;Bạn chỉ c&oacute; thể tải l&ecirc;n v&ugrave;ng tương t&aacute;c bất kỳ hoặc truyền, gửi, c&ocirc;ng bố, m&ocirc; phỏng hoặc ph&acirc;n phối tr&ecirc;n hoặc th&ocirc;ng qua Website TopDev phần nội dung, kh&ocirc;ng phụ thuộc v&agrave;o bất kỳ Quyền Sở hữu Tr&iacute; tuệ n&agrave;o, hoặc nội dung m&agrave; người giữ Quyền Sở hữu Tr&iacute; tuệ c&oacute; sự ủy quyền r&otilde; r&agrave;ng về việc ph&acirc;n t&aacute;n tr&ecirc;n Internet v&agrave; tr&ecirc;n Website TopDev m&agrave; kh&ocirc;ng c&oacute; hạn chế g&igrave;. Mọi nội dung được đưa ra với sự đồng &yacute; của người sở hữu bản quyền kh&ocirc;ng phải l&agrave; bạn phải k&egrave;m theo c&acirc;u như &ldquo;do [t&ecirc;n người chủ sở hữu] sở hữu bản quyền; được d&ugrave;ng theo ủy quyền&rdquo;. Với việc đưa nội dung l&ecirc;n v&ugrave;ng tương t&aacute;c bất kỳ, bạn tự động chấp nhận v&agrave;/hoặc cam đoan rằng, chủ sở hữu của nội dung đ&oacute;, hoặc l&agrave; bạn, hoặc l&agrave; nh&oacute;m thứ ba, đ&atilde; cho Website TopDev quyền v&agrave; giấy ph&eacute;p kh&ocirc;ng phải trả tiền bản quyền, l&acirc;u d&agrave;i, kh&ocirc;ng thay đổi, kh&ocirc;ng loại trừ, kh&ocirc;ng hạn chế để sử dụng, m&ocirc; phỏng, thay đổi, sửa lại, c&ocirc;ng bố, dịch thuật, tạo c&aacute;c sản phẩm ph&aacute;i sinh, cấp ph&eacute;p con, ph&acirc;n phối, thực hiện v&agrave; hiển thị nội dung đ&oacute;, to&agrave;n phần hay từng phần, khắp thế giới v&agrave;/hoặc kết hợp n&oacute; với c&aacute;c c&ocirc;ng việc kh&aacute;c ở dạng bất kỳ, qua c&aacute;c phương tiện truyền th&ocirc;ng hoặc c&ocirc;ng nghệ hiện tại hay sẽ ph&aacute;t triển sau n&agrave;y theo điều khoản đầy đủ của Quyền Sở hữu Tr&iacute; tuệ bất kỳ trong nội dung đ&oacute;. Bạn cũng cho ph&eacute;p Website TopDev cấp giấy ph&eacute;p con cho b&ecirc;n thứ ba quyền kh&ocirc;ng hạn chế để thực hiện bất kỳ quyền n&agrave;o ở tr&ecirc;n với nội dung đ&oacute;. Bạn cũng cho ph&eacute;p Website TopDev d&ugrave;ng t&ecirc;n v&agrave; logo c&ocirc;ng ty v&igrave; c&aacute;c mục đ&iacute;ch tiếp thị.</span></p>

<p><span style="font-size:18px"><strong>C&aacute;c Li&ecirc;n Kết, Từ Chối C&aacute;c Bảo Đảm, Giới Hạn Tr&aacute;ch Nhiệm</strong></span></p>

<p><span style="font-size:14px">&nbsp; &nbsp; &nbsp; &nbsp;<strong>C&aacute;c li&ecirc;n kết.</strong>&nbsp;Bạn hiểu rằng trừ phần nội dung, c&aacute;c sản phẩm v&agrave; dịch vụ c&oacute; tr&ecirc;n Website TopDev, TopDev.vn, c&ocirc;ng ty mẹ, hoặc c&aacute;c chi nh&aacute;nh, cũng như c&aacute;c gi&aacute;m đốc, nh&acirc;n vi&ecirc;n, người l&agrave;m c&ocirc;ng v&agrave; c&aacute;c đại l&yacute; tương ứng kiểm so&aacute;t, cung cấp kh&ocirc;ng chịu tr&aacute;ch nhiệm với nội dung, h&agrave;ng h&oacute;a hoặc c&aacute;c dịch vụ của c&aacute;c sites kh&aacute;c tr&ecirc;n Internet được kết nối đến hoặc từ Website TopDev. Tất cả nội dung, h&agrave;ng h&oacute;a v&agrave; c&aacute;c dịch vụ đ&oacute; đều c&oacute; thể truy cập được tr&ecirc;n Internet bởi b&ecirc;n thứ ba độc lập v&agrave; kh&ocirc;ng phải l&agrave; một phần của Website TopDev hoặc được kiểm so&aacute;t bởi TopDev.vn. Website TopDev kh&ocirc;ng x&aacute;c nhận v&agrave; cũng kh&ocirc;ng chịu tr&aacute;ch nhiệm về t&iacute;nh ch&iacute;nh x&aacute;c, t&iacute;nh đầy đủ, t&iacute;nh hữu dụng, chất lượng v&agrave; t&iacute;nh sẵn s&agrave;ng của mọi nội dung, h&agrave;ng h&oacute;a hay c&aacute;c dịch vụ c&oacute; tr&ecirc;n c&aacute;c site được kết nối đến hoặc từ Website TopDev m&agrave; đ&oacute; l&agrave; tr&aacute;ch nhiệm duy nhất của b&ecirc;n thứ ba độc lập đ&oacute;, v&agrave; do vậy việc sử dụng của bạn l&agrave; sự mạo hiểm ri&ecirc;ng của bạn. Website TopDev, c&ocirc;ng ty mẹ, hoặc c&aacute;c chi nh&aacute;nh, hoặc c&aacute;c gi&aacute;m đốc, nh&acirc;n vi&ecirc;n, người l&agrave;m c&ocirc;ng v&agrave; c&aacute;c đại l&yacute; tương ứng kh&ocirc;ng chịu tr&aacute;ch nhiệm ph&aacute;p l&yacute;, trực tiếp hay gi&aacute;n tiếp, với mọi mất m&aacute;t hay thiệt hại g&acirc;y ra bởi hoặc bị cho l&agrave; g&acirc;y ra bởi việc sử dụng hoặc sự tin cậy của bạn v&agrave;o mọi nội dung, h&agrave;ng h&oacute;a hoặc c&aacute;c dịch vụ c&oacute; tr&ecirc;n site bất kỳ được kết nối đến hoặc từ Website TopDev, hoặc do bạn kh&ocirc;ng thể truy cập l&ecirc;n Internet hay site bất kỳ kết nối đến hoặc từ Website TopDev.</span></p>

<p><span style="font-size:14px">&nbsp; &nbsp; &nbsp; &nbsp;<strong>Từ chối c&aacute;c bảo đảm.</strong>&nbsp;Xin h&atilde;y d&ugrave;ng sự suy x&eacute;t tốt nhất của bạn trong việc đ&aacute;nh gi&aacute; tất cả c&aacute;c th&ocirc;ng tin hoặc c&aacute;c &yacute; kiến được tr&igrave;nh b&agrave;y tr&ecirc;n Website TopDev. Ch&iacute;nh s&aacute;ch của Website TopDev kh&ocirc;ng x&aacute;c nhận hay phản đối mọi &yacute; kiến do người sử dụng b&agrave;y tỏ, hoặc nội dung do nh&oacute;m độc lập kh&aacute;c cung cấp. BẠN ĐỒNG &Yacute; R&Otilde; R&Agrave;NG RẰNG VIỆC SỬ DỤNG Website TopDev L&Agrave; SỰ MẠO HIỂM CỦA RI&Ecirc;NG BẠN. Website TopDev, V&Agrave; C&Ocirc;NG TY MẸ, HOẶC C&Aacute;C CHI NH&Aacute;NH, HOẶC C&Aacute;C GI&Aacute;M ĐỐC, NH&Acirc;N VI&Ecirc;N, NHỮNG NGƯỜI L&Agrave;M THU&Ecirc;, C&Aacute;C ĐẠI L&Yacute;, C&Aacute;C CỘNG T&Aacute;C VI&Ecirc;N, HỘI VI&Ecirc;N, NGƯỜI CẤP PH&Eacute;P HOẶC C&Aacute;C NH&Agrave; CUNG CẤP KH&Aacute;C CUNG CẤP NỘI DUNG, DỮ LIỆU, TH&Ocirc;NG TIN HOẶC C&Aacute;C DỊCH VỤ KH&Ocirc;NG BẢO ĐẢM RẰNG, Website TopDev HOẶC MỌI SITE INTERNET ĐƯỢC KẾT NỐI ĐẾN HOẶC TỪ Website TopDev SẼ KH&Ocirc;NG BỊ NGẮT QU&Atilde;NG HOẶC BỊ SAI S&Oacute;T, RẰNG C&Aacute;C NHƯỢC ĐIỂM SẼ ĐƯỢC SỬA CHỮA, HOẶC SITE N&Agrave;Y, KỂ CẢ C&Aacute;C V&Ugrave;NG TƯƠNG T&Aacute;C HOẶC M&Aacute;Y CHỦ TẠO RA N&Oacute; KH&Ocirc;NG BỊ NHIỄM VIRUS HAY C&Aacute;C TH&Agrave;NH PHẦN G&Acirc;Y HẠI KH&Aacute;C. V&Agrave; CH&Uacute;NG T&Ocirc;I CŨNG KH&Ocirc;NG BẢO ĐẢM VỀ C&Aacute;C KẾT QUẢ NHẬN ĐƯỢC TỪ VIỆC SỬ DỤNG Website TopDev HOẶC VỀ T&Iacute;NH Đ&Uacute;NG L&Uacute;C, T&Iacute;NH TR&Igrave;NH TỰ, T&Iacute;NH CH&Iacute;NH X&Aacute;C, SỰ ỦY QUYỀN, T&Iacute;NH ĐẦY ĐỦ, T&Iacute;NH HỮU DỤNG, T&Iacute;NH BẤT KHẢ X&Acirc;M PHẠM, T&Iacute;NH TIN CẬY, T&Iacute;NH SẴN S&Agrave;NG HOẶC T&Iacute;NH CHẮC CHẮN CỦA MOI NỘI DUNG, TH&Ocirc;NG TIN, DỊCH VỤ HOẶC GIAO DỊCH ĐƯỢC CUNG CẤP QUA Website TopDev HOẶC MỌI SITE ĐƯỢC KẾT NỐI ĐẾN HOẶC TỪ Website TopDev. Website TopDev ĐƯỢC CUNG CẤP TR&Ecirc;N CƠ SỞ &ldquo;VỚI TƯ C&Aacute;CH L&Agrave;&rdquo;, &ldquo;NẾU C&Oacute;&rdquo; M&Agrave; KH&Ocirc;NG C&Oacute; BẤT KỲ ĐẢM BẢO THEO H&Igrave;NH THỨC N&Agrave;O, R&Otilde; R&Agrave;NG HAY NGỤ &Yacute;, BAO GỒM NHƯNG KH&Ocirc;NG HẠN CHẾ, C&Aacute;C VẤN ĐỀ C&Oacute; T&Iacute;NH THƯƠNG MẠI HAY PH&Ugrave; HỢP CHO MỘT MỤC Đ&Iacute;CH CỤ THỂ.</span></p>

<p><span style="font-size:14px">&nbsp; &nbsp; &nbsp; &nbsp;<strong>Giới hạn về tr&aacute;ch nhiệm ph&aacute;p l&yacute;.</strong>&nbsp;TRONG BẤT KỲ TRƯỜNG HỢP N&Agrave;O, Website TopDev, C&Ocirc;NG TY MẸ, HOẶC C&Aacute;C CHI NH&Aacute;NH, HOẶC C&Aacute;C GI&Aacute;M ĐỐC, NH&Acirc;N VI&Ecirc;N, NHỮNG NGƯỜI L&Agrave;M THU&Ecirc;, C&Aacute;C ĐẠI L&Yacute;, C&Aacute;C CỘNG T&Aacute;C VI&Ecirc;N, HOẶC NHỮNG NGƯỜI CẤP PH&Eacute;P KH&Ocirc;NG CHỊU TR&Aacute;CH NHIỆM PH&Aacute;P L&Yacute; VỚI MỌI THIỆT HẠI NGẪU NHI&Ecirc;N, ĐẶC BIỆT HAY ĐƯƠNG NHI&Ecirc;N THEO HOẶC NẢY SINH TỪ BẢN THỎA THUẬN N&Agrave;Y, Website TopDev HOẶC MỌI SITE INTERNET ĐƯỢC KẾT NỐI ĐẾN HOẶC TỪ Website TopDev, V&Igrave; L&Yacute; DO VI PHẠM HỢP ĐỒNG, ỨNG XỬ SAI LẦM, SƠ XUẤT HOẶC BẤT KỲ NGUY&Ecirc;N NH&Acirc;N H&Agrave;NH ĐỘNG KH&Aacute;C N&Agrave;O, BAO GỒM NHƯNG KH&Ocirc;NG HẠN CHẾ MỌI NGHĨA VỤ PH&Aacute;P L&Yacute; CHO MỌI THIỆT HẠI G&Acirc;Y BỞI HOẶC CHO L&Agrave; G&Acirc;Y BỞI MỌI THIẾU S&Oacute;T TRONG THỰC HIỆN, LỖI BỎ S&Oacute;T, GI&Aacute;N ĐOẠN, SỰ ĐỘT BIẾN/HỎNG H&Oacute;C/NHIỄU ĐIỆN, VIỆC X&Oacute;A, CHẬM TRỄ TRONG HOẠT ĐỘNG HOẶC CHUYỂN TẢI, VIRUT M&Aacute;Y T&Iacute;NH, HỎNG ĐƯỜNG LI&Ecirc;N LẠC, HỎNG THIẾT BỊ, LỖI PHẦN MỀM, VI PHẠM, TRUY CẬP TR&Aacute;I PH&Eacute;P, HOẶC TRỘM CẮP, PH&Aacute; HOẠI, THAY THẾ, HOẶC SỬ DỤNG C&Aacute;C BẢN GHI.</span></p>

<p><span style="font-size:14px">&nbsp; &nbsp; &nbsp; &nbsp;TRONG BẤT KỲ TRƯỜNG HỢP N&Agrave;O, Website TopDev, C&Ocirc;NG TY MẸ, HOẶC C&Aacute;C CHI NH&Aacute;NH, HOẶC C&Aacute;C GI&Aacute;M ĐỐC, NH&Acirc;N VI&Ecirc;N, NHỮNG NGƯỜI L&Agrave;M THU&Ecirc;, C&Aacute;C ĐẠI L&Yacute;, C&Aacute;C CỘNG T&Aacute;C VI&Ecirc;N HOẶC NHỮNG NGƯỜI CẤP PH&Eacute;P KH&Ocirc;NG CHỊU TR&Aacute;CH NHIỆM PH&Aacute;P L&Yacute; ĐỐI VỚI BẠN HOẶC MỌI NH&Oacute;M THỨ BA KH&Aacute;C VỀ MỌI QUYẾT ĐỊNH Đ&Atilde; RA HOẶC H&Agrave;NH ĐỘNG M&Agrave; BẠN THỰC HIỆN V&Igrave; TIN V&Agrave;O NỘI DUNG CHỨA TRONG Website TopDev HOẶC NỘI DUNG CH&Uacute;NG ĐỰNG TRONG PHẠM VI MỌI SITE INTERNET ĐƯỢC KẾT NỐI VỚI HOẶC TỪ Website TopDev. NỘI DUNG TRONG PHẠM VI Website TopDev V&Agrave; NỘI DUNG TRONG PHẠM VI C&Aacute;C SITE INTERNET ĐƯỢC KẾT NỐI ĐẾN HOẶC TỪ Website TopDev C&Oacute; THỂ C&Oacute; LỖI KỸ THUẬT, C&Aacute;C LỖI KH&Ocirc;NG CH&Iacute;NH X&Aacute;C KH&Aacute;C, HOẶC C&Aacute;C LỖI IN.</span></p>

<p><span style="font-size:14px">&nbsp; &nbsp; &nbsp; &nbsp;BẠN ĐỒNG &Yacute; V&Agrave; THỪA NHẬN R&Otilde; R&Agrave;NG RẰNG, Website TopDev KH&Ocirc;NG CHỊU TR&Aacute;CH NHIỆM PH&Aacute;P L&Yacute; VỚI MỌI H&Agrave;NH VI N&Oacute;I XẤU, TẤN C&Ocirc;NG, KH&Ocirc;NG TRUNG THỰC HOẶC CẤC H&Agrave;NH VI BẤT HỢP PH&Aacute;P KH&Aacute;C CỦA NGƯỜI SỬ DỤNG BẤT KỲ. NẾU BẠN KH&Ocirc;NG BẰNG L&Ograve;NG VỚI BẤT KỲ NỘI DUNG N&Agrave;O CỦA Website TopDev, HOẶC VỚI GIAO K&Egrave;O TRUY CẬP CỦA Website TopDev, TO&Agrave;N BỘ HAY TỪNG PHẦN, TH&Igrave; BIỆN PH&Aacute;P DUY NHẤT CỦA BẠN L&Agrave; TH&Ocirc;I KH&Ocirc;NG SỬ DỤNG Website TopDev NỮA.</span></p>

<p><span style="font-size:18px"><strong>Tu&acirc;n Thủ V&agrave; Xử L&yacute; Vi Phạm</strong></span></p>

<p><span style="font-size:14px">&nbsp; &nbsp; &nbsp; &nbsp;Bạn phải tu&acirc;n thủ đ&uacute;ng c&aacute;c quy định tại Đơn đặt h&agrave;ng, Hợp đồng Dịch vụ, bản Điều khoản &amp; Điều kiện n&agrave;y như l&agrave; điều kiện ti&ecirc;n quyết cho việc sử dụng Dịch vụ. Trường hợp bạn vi phạm bất kỳ quy định n&ecirc;u tại Đơn đặt h&agrave;ng, Hợp đồng Dịch vụ v&agrave; bản Điều Kiện &amp; Điều Khoản n&agrave;y, th&igrave; ch&uacute;ng t&ocirc;i c&oacute; quyền gỡ bỏ mọi đăng tuyển, nội dung hoặc đường dẫn của bạn v&agrave; chấm dứt việc cung cấp dịch vụ m&agrave; kh&ocirc;ng phải trả lại Ph&iacute; Dịch vụ hoặc số tiền dịch vụ m&agrave; bạn đ&atilde; thanh to&aacute;n nhưng chưa sử dụng hết. Đồng thời, ch&uacute;ng t&ocirc;i c&oacute; quyền buộc bạn bồi thường thiệt hại hoặc mất m&aacute;t ph&aacute;t sinh từ vi phạm của bạn.</span></p>

<p><span style="font-size:18px"><strong>Bồi Thường</strong></span></p>

<p><span style="font-size:14px">&nbsp; &nbsp; &nbsp; &nbsp;Bạn đồng &yacute; trả tiền v&agrave; miễn cho Website TopDev, c&ocirc;ng ty mẹ hoặc c&ocirc;ng ty con v&agrave; c&aacute;c chi nh&aacute;nh, c&aacute;c gi&aacute;m đốc, nh&acirc;n vi&ecirc;n, những người l&agrave;m c&ocirc;ng v&agrave; c&aacute;c đại l&yacute; của Website TopDev khỏi c&aacute;c tr&aacute;ch nhiệm ph&aacute;p l&yacute;, khiếu kiện v&agrave; c&aacute;c ph&iacute; tổn, kể cả c&aacute;c ph&iacute; hợp l&yacute; cho luật sư, nảy sinh từ sự vi phạm bản Thỏa thuận n&agrave;y, từ ch&iacute;nh s&aacute;ch bất kỳ kh&aacute;c, từ việc bạn sử dụng hay truy cập Website TopDev hoặc site internet đựơc kết nối đến hoặc từ Website TopDev, hoặc về việc truyền nội dung bất kỳ tr&ecirc;n Website TopDev.</span></p>

<p><span style="font-size:18px"><strong>Bảo Mật</strong></span></p>

<p><span style="font-size:14px">&nbsp; &nbsp; &nbsp; &nbsp;Bạn đồng &yacute; với cam kết bảo mật th&ocirc;ng tin li&ecirc;n quan đến Dịch vụ, việc thực hiện giao dịch, v&agrave;/hoặc bất kỳ th&ocirc;ng tin kh&aacute;c thu thập được từ việc thực hiện giao dịch. Bạn sẽ hợp t&aacute;c ngăn chặn v&agrave; chống lại h&agrave;nh vi của bất kỳ b&ecirc;n thứ ba n&agrave;o sao ch&eacute;p v&agrave; sử dụng tr&aacute;i ph&eacute;p nội dung đăng tuyển hoặc th&ocirc;ng tin kh&aacute;c của bạn tr&ecirc;n Internet.</span></p>

<p><span style="font-size:14px">&nbsp; &nbsp; &nbsp; &nbsp;Bạn kh&ocirc;ng được tiết lộ, chia sẻ hoặc b&aacute;n c&aacute;c th&ocirc;ng tin về ứng vi&ecirc;n m&agrave; m&igrave;nh thu thập được từ việc sử dụng dịch vụ cho bất kỳ một b&ecirc;n thứ ba n&agrave;o kh&aacute;c dưới mọi h&igrave;nh thức m&agrave; kh&ocirc;ng được sự đồng &yacute; trước bằng văn bản của C&ocirc;ng Ty.</span></p>

<p><span style="font-size:14px">&nbsp; &nbsp; &nbsp; &nbsp;Ngo&agrave;i ra, Kh&aacute;ch H&agrave;ng c&oacute; tr&aacute;ch nhiệm bảo mật t&agrave;i khoản v&agrave; mật khẩu, v&agrave; chỉ sử dụng t&agrave;i khoản cho mục đ&iacute;ch tuyển dụng của m&igrave;nh theo thỏa thuận quy định tại Đơn đặt h&agrave;ng/Hợp đồng Dịch vụ.</span></p>

<p><span style="font-size:18px"><strong>C&aacute;c Vấn Đề Kh&aacute;c</strong></span></p>

<p><span style="font-size:14px">&nbsp; &nbsp; &nbsp; &nbsp;Bản thoả thuận n&agrave;y bao gồm to&agrave;n bộ sự thoả thuận giữa Website TopDev v&agrave; bạn, v&agrave; thay thế mọi thoả thuận trước đ&acirc;y về chủ đề n&agrave;y. Website TopDev c&oacute; thể sửa đổi bản Thoả thuận n&agrave;y hoặc bất kỳ ch&iacute;nh s&aacute;ch kh&aacute;c v&agrave;o bất cứ l&uacute;c n&agrave;o v&agrave; t&ugrave;y từng thời điểm, v&agrave; sự sửa đổi n&agrave;y sẽ tức th&igrave; c&oacute; hiệu lực ngay khi th&ocirc;ng b&aacute;o về sự sửa đổi đ&oacute; được c&ocirc;ng bố ở nơi dễ thấy tr&ecirc;n Website TopDev.</span></p>

<p><span style="font-size:14px">&nbsp; &nbsp; &nbsp; &nbsp;Bạn đồng &yacute; xem lại bản Thoả thuận n&agrave;y định kỳ để nhận biết được những điều đ&atilde; được sửa đổi. Nếu bạn kh&ocirc;ng chấp nhận c&aacute;c sửa đổi n&agrave;y, bạn phải ngưng truy cập Website TopDev. Sự tiếp tục truy cập của bạn v&agrave; việc sử dụng Website TopDev sau th&ocirc;ng b&aacute;o về mọi sửa đổi như vậy sẽ được xem l&agrave; sự chấp nhận tất cả c&aacute;c sửa đổi như vậy.</span></p>

<p><span style="font-size:14px">&nbsp; &nbsp; &nbsp; &nbsp;Nếu điều khoản bất kỳ của bản Thoả thuận n&agrave;y hoặc của mọi ch&iacute;nh s&aacute;ch kh&aacute;c kh&ocirc;ng c&oacute; hiệu lực hoặc kh&ocirc;ng thể thực hiện được, th&igrave; phần nội dung đ&oacute; sẽ được giải th&iacute;ch theo luật hiện h&agrave;nh gần nhất c&oacute; thể để phản &aacute;nh mục đ&iacute;ch ban đầu của c&aacute;c b&ecirc;n v&agrave; c&aacute;c phần c&ograve;n lại sẽ tiếp tục c&oacute; đầy đủ hiệu hiệu lực. Việc Website TopDev kh&ocirc;ng thể đ&ograve;i hỏi hoặc buộc thực hiện chặt chẽ mọi điều khoản của bản Thoả thuận n&agrave;y sẽ kh&ocirc;ng được coi l&agrave; sự khước từ điều khoản hay quyền bất kỳ. Bản Thoả thuận n&agrave;y sẽ được điều chỉnh bởi c&aacute;c luật của bang hay tỉnh sở tại của Website TopDev, trừ phi c&oacute; sự m&acirc;u thuẫn c&aacute;c quy tắc của c&aacute;c luật, v&agrave; bạn v&agrave; Website TopDev đều phải phục t&ugrave;ng quyền thực thi ph&aacute;p l&yacute; duy nhất của to&agrave; &aacute;n tỉnh hay bang đ&oacute;.</span></p>

<p><span style="font-size:14px">&nbsp; &nbsp; &nbsp; &nbsp;Bản Thoả thuận n&agrave;y l&agrave; d&agrave;nh ri&ecirc;ng cho bạn v&agrave; bạn kh&ocirc;ng thể chuyển c&aacute;c quyền của bạn, hoặc nghĩa vụ cho bất kỳ ai. Tất cả c&aacute;c logo, t&ecirc;n chi nh&aacute;nh, c&aacute;c sản phẩm, t&ecirc;n thương mại hay c&aacute;c nh&atilde;n hiệu dịch vụ xuất hiện ở đ&acirc;y c&oacute; thể l&agrave; c&aacute;c t&ecirc;n thương mại hay c&aacute;c nh&atilde;n dịchvụ của c&aacute;c chủ sở hữu tương ứng của ch&uacute;ng. C&aacute;c tham chiếu đến t&ecirc;n thương mại bất kỳ, nh&atilde;n hiệu dịch vụ v&agrave; c&aacute;c li&ecirc;n kết đến hoặc từ Website TopDev đều được thực hiện chặt chẽ để l&agrave;m r&otilde; v&agrave; nhận dạng v&agrave; kh&ocirc;ng cấu th&agrave;nh sự chứng thực của Website TopDev về c&aacute;c sản phẩm, dịch vụ hoặc th&ocirc;ng tin do người chủ sở hữu của t&ecirc;n thương mại, nh&atilde;n dịch vụ, hoặc li&ecirc;n kết, đề nghị hoặc sự chứng thực của Website TopDev bởi người sở hữu c&aacute;c sản phẩm, dịch vụ hoặc li&ecirc;n kết đ&oacute;.</span></p>
</div>
@endsection